# Generated by Django 4.2.13 on 2024-06-08 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-room_id"]},
        ),
    ]
