# Generated by Django 4.2.13 on 2024-06-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streaming", "0002_alter_room_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="room",
            name="streamer_id",
            field=models.CharField(max_length=36),
        ),
    ]
