name: Restrict Feat Branch Merges

on:
  pull_request:
    branches:
      - '*-feat'

jobs:
  restrict-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check target branch
        run: |
          TARGET_BRANCH=${{ github.event.pull_request.base.ref }}
          if [[ ! "$TARGET_BRANCH" =~ ^.*-dev$ ]]; then
            echo "You can only merge '*-feat' branches into '*-dev' branches."
            exit 1
          fi
